#ifndef OSUDIRECT_H
#define OSUDIRECT_H
#include <esp_http_server.h>

// XXX: This might be changed if memory starts being an issue
#define OSU_DIRECT_MAP_CHUNK_SIZE 8096

// Certificate for catboy.best, as of 2025-08-05
// XXX: If this has been changed then request will fail.
// You might need to get the newer certificate chain
// Linux command to get new cert:
// openssl s_client -showcerts -connect catboy.best:443 -servername catboy.best < /dev/null 2>/dev/null | sed -n '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----/p' | tail -n +1 > root_ca.pem
const char* mirrorCaPem =
"-----BEGIN CERTIFICATE-----\n"
"MIIDuTCCA0CgAwIBAgISBu5vthxDv1RnaP67/G3ZShSBMAoGCCqGSM49BAMDMDIx\n"
"CzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQDEwJF\n"
"NTAeFw0yNTA3MDUxOTIyNDFaFw0yNTEwMDMxOTIyNDBaMBYxFDASBgNVBAMTC2Nh\n"
"dGJveS5iZXN0MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEVumVJ7umE9uKkmAk\n"
"oM1HeQSDmtQsMW962GwuNRu18qpMBxxd356Qchea4RKbjIGu5JZRPWzVo75RSwsc\n"
"zbytK6OCAlAwggJMMA4GA1UdDwEB/wQEAwIHgDAdBgNVHSUEFjAUBggrBgEFBQcD\n"
"AQYIKwYBBQUHAwIwDAYDVR0TAQH/BAIwADAdBgNVHQ4EFgQU8mAZr4SRMFFONxNV\n"
"oJ6DkyVwvvQwHwYDVR0jBBgwFoAUnytfzzwhT50Et+0rLMTGcIvS1w0wMgYIKwYB\n"
"BQUHAQEEJjAkMCIGCCsGAQUFBzAChhZodHRwOi8vZTUuaS5sZW5jci5vcmcvME0G\n"
"A1UdEQRGMESCEyouYmVhdG1hcHMuZG93bmxvYWSCDSouY2F0Ym95LmJlc3SCEWJl\n"
"YXRtYXBzLmRvd25sb2FkggtjYXRib3kuYmVzdDATBgNVHSAEDDAKMAgGBmeBDAEC\n"
"ATAsBgNVHR8EJTAjMCGgH6AdhhtodHRwOi8vZTUuYy5sZW5jci5vcmcvMi5jcmww\n"
"ggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwB9WR4S4XgqexxhZ3xe/fjQh1wUoE6V\n"
"nrkDL9kOjC55uAAAAZfcP/94AAAEAwBIMEYCIQCjTWDhdE1zloZdxoKxYD8yTY/v\n"
"LmBYsvL0MGjFYc1QYAIhAIXqs3GT2uUWjH0nFJcE7zYG21c14e8FBlOebjtUChSQ\n"
"AHYA3dzKNJXX4RYF55Uy+sef+D0cUN/bADoUEnYKLKy7yCoAAAGX3EAHbwAABAMA\n"
"RzBFAiB+y5SSWcVz0NYc1v0z6QU1N5mocmWnoEghgUkNT7/G1AIhAKWUXFCXuw4Y\n"
"639050UuLs5ofRDdGIKMUESDTwlZVRtXMAoGCCqGSM49BAMDA2cAMGQCMGxv3/uJ\n"
"QefGNRJ39/4hVppMToWGBsl/ZpATgPte+KMFpkwIOvSptJrQAnlSCL7TVgIwSEBB\n"
"on9z/DUR0gmN/PF5jE+olRr8LMCd86QLrJS1rjBz9U8CRzgk6Pft59NTA/5Y\n"
"-----END CERTIFICATE-----\n"
"-----BEGIN CERTIFICATE-----\n"
"MIIEVzCCAj+gAwIBAgIRAIOPbGPOsTmMYgZigxXJ/d4wDQYJKoZIhvcNAQELBQAw\n"
"TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh\n"
"cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjQwMzEzMDAwMDAw\n"
"WhcNMjcwMzEyMjM1OTU5WjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg\n"
"RW5jcnlwdDELMAkGA1UEAxMCRTUwdjAQBgcqhkjOPQIBBgUrgQQAIgNiAAQNCzqK\n"
"a2GOtu/cX1jnxkJFVKtj9mZhSAouWXW0gQI3ULc/FnncmOyhKJdyIBwsz9V8UiBO\n"
"VHhbhBRrwJCuhezAUUE8Wod/Bk3U/mDR+mwt4X2VEIiiCFQPmRpM5uoKrNijgfgw\n"
"gfUwDgYDVR0PAQH/BAQDAgGGMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcD\n"
"ATASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBSfK1/PPCFPnQS37SssxMZw\n"
"i9LXDTAfBgNVHSMEGDAWgBR5tFnme7bl5AFzgAiIyBpY9umbbjAyBggrBgEFBQcB\n"
"AQQmMCQwIgYIKwYBBQUHMAKGFmh0dHA6Ly94MS5pLmxlbmNyLm9yZy8wEwYDVR0g\n"
"BAwwCjAIBgZngQwBAgEwJwYDVR0fBCAwHjAcoBqgGIYWaHR0cDovL3gxLmMubGVu\n"
"Y3Iub3JnLzANBgkqhkiG9w0BAQsFAAOCAgEAH3KdNEVCQdqk0LKyuNImTKdRJY1C\n"
"2uw2SJajuhqkyGPY8C+zzsufZ+mgnhnq1A2KVQOSykOEnUbx1cy637rBAihx97r+\n"
"bcwbZM6sTDIaEriR/PLk6LKs9Be0uoVxgOKDcpG9svD33J+G9Lcfv1K9luDmSTgG\n"
"6XNFIN5vfI5gs/lMPyojEMdIzK9blcl2/1vKxO8WGCcjvsQ1nJ/Pwt8LQZBfOFyV\n"
"XP8ubAp/au3dc4EKWG9MO5zcx1qT9+NXRGdVWxGvmBFRAajciMfXME1ZuGmk3/GO\n"
"koAM7ZkjZmleyokP1LGzmfJcUd9s7eeu1/9/eg5XlXd/55GtYjAM+C4DG5i7eaNq\n"
"cm2F+yxYIPt6cbbtYVNJCGfHWqHEQ4FYStUyFnv8sjyqU8ypgZaNJ9aVcWSICLOI\n"
"E1/Qv/7oKsnZCWJ926wU6RqG1OYPGOi1zuABhLw61cuPVDT28nQS/e6z95cJXq0e\n"
"K1BcaJ6fJZsmbjRgD5p3mvEf5vdQM7MCEvU0tHbsx2I5mHHJoABHb8KVBgWp/lcX\n"
"GWiWaeOyB7RP+OfDtvi2OsapxXiV7vNVs7fMlrRjY1joKaqmmycnBvAq14AEbtyL\n"
"sVfOS66B8apkeFX2NY4XPEYV4ZSCe8VHPrdrERk2wILG3T/EGmSIkCYVUMSnjmJd\n"
"VQD9F6Na/+zmXCc=\n"
"-----END CERTIFICATE-----\n";

esp_err_t directSearchHandler(httpd_req_t *req);
esp_err_t directDownloadHandler(httpd_req_t *req);

#endif //OSUDIRECT_H
