#ifndef BANCHOPACKETS_H
#define BANCHOPACKETS_H


// PLEASE READ THE b338 ENUM ORDER PLZZZZZZZZZZZ
// Don't let the UserStats incident happen again
#define CHO_PACKET_CHANGE_STATUS 0
#define CHO_PACKET_REQUEST_STATUS 3
#define CHO_PACKET_PONG 4
#define CHO_PACKET_LOGINREPLY 5
#define CHO_PACKET_PING 8
#define CHO_PACKET_USER_STATS 12
#define CHO_PACKET_CHANNEL_JOIN_SUCCESS 65
#define CHO_PACKET_CHANNEL_AVAILABLE 66
#define CHO_PACKET_CHANNEL_AVAILABLE_AUTOJOIN 68
#define CHO_PACKET_RECEIVE_UPDATES 80

#endif
